version: '3'

services:
  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    environment:
      - CASSANDRA_CLUSTER_NAME=docker-cluster
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_LISTEN_ADDRESS=cassandra-1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_START_RPC=true
    ports:
      - 9042:9042
    volumes:
      - ./data/cassandra-1:/var/lib/cassandra
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'

  cassandra-2:
    image: cassandra:latest
    container_name: cassandra-2
    environment:
      - CASSANDRA_CLUSTER_NAME=docker-cluster
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_LISTEN_ADDRESS=cassandra-2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_START_RPC=true
    ports:
      - 9043:9042
    volumes:
      - ./data/cassandra-2:/var/lib/cassandra
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'

  cassandra-3:
    image: cassandra:latest
    container_name: cassandra-3
    environment:
      - CASSANDRA_CLUSTER_NAME=docker-cluster
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_LISTEN_ADDRESS=cassandra-3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_START_RPC=true
    ports:
      - 9044:9042
    volumes:
      - ./data/cassandra-3:/var/lib/cassandra
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'
